<a href="https://colab.research.google.com/github/harshithard/ComputerVision/blob/main/test_HOG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def calculate_histogram(array, weights):
  hist = np.zeros(9)
  weights = np.asarray(weights,dtype=float)
  array = np.asarray(array,dtype=float)

  #print(weights)
  centers = [10.0,30.0,50.0,70.0,90.0,110.0,130.0,150.0,170.0]
  bin1 = 0
  bin2 = 0
  proportion1=0.0
  proportion2 = 0.0
  for i in range(3):
      for j in range(3):
        if(array[i][j] in centers):
          proportion1 = 1.0
          proportion2 = 0.0
          bin1 = int(array[i][j]//20)

        elif(array[i][j]%20==0): #test corners
          proportion1 = 0.5
          proportion2 = 0.5
          if(array[i][j]==180.0 or array[i][j]==0.0):
            bin1 = 0
            bin2 = 8
          else:
            bin1 = math.ceil((array[i][j]/20)+0.05) - 1
            #hist[bin1] += 0.5*weights[i][j]
            #hist[bin1-1] += 0.5*weights[i][j]
            bin2 = bin1-1
        else:
          bin1 = math.ceil((array[i][j]/20)) - 1
          if(bin1==9):
            bin1 = 0
            bin2 = 8
          else:
            if(bin1==8 and array[i][j]>centers[bin1]):
              bin2 = 0
            elif(array[i][j]<centers[bin1] and bin1==0):
              bin2 = 8
            elif(array[i][j]<centers[bin1]):
              bin2 = bin1-1
            else:
              bin2 = bin1+1
          proportion1 = 1 - (abs(array[i][j]-centers[bin1])/20.0)

          proportion2 = 1-proportion1

        hist[bin1] = hist[bin1] + (proportion1*weights[i][j])
        hist[bin2] = hist[bin2] + (proportion2*weights[i][j])
  #hist,_ = np.histogram(array,bins=9,range=(0,180),weights=weights)
  #print(hist)
  return hist

In [ ]:
cell = [3, 3]
incr = [3,3]
bin_num = 9
im_size = [6,6]

def create_hog_features(grad_array,mag_array):
  max_h = int(((grad_array.shape[0]-cell[0])/incr[0])+1)
  max_w = int(((grad_array.shape[1]-cell[1])/incr[1])+1)
  cell_array = []
  w = 0
  h = 0
  i = 0
  j = 0
  #Creating 8X8 cells
  while i<max_h:
    w = 0
    j = 0

    while j<max_w:
      gradient_array = grad_array[h:h+cell[0],w:w+cell[1]]
      print(gradient_array)
      magnitude_array = mag_array[h:h+cell[0],w:w+cell[1]]
      print(magnitude_array)
      val = calculate_histogram(gradient_array,magnitude_array)
      print(val)
      cell_array.append(val)
      j += 1
      w += incr[1]
    i += 1
    h += incr[0]

  cell_array = np.reshape(cell_array,(max_h, max_w, bin_num))
	#normalising blocks of cells
  block = [2,2]
	#here increment is 1

  max_h = int((max_h-block[0])+1)
  max_w = int((max_w-block[1])+1)
  #max_h = 19
  #max_w = 11
  block_list = []
  w = 0
  h = 0
  i = 0
  j = 0
  
  while i<max_h:
    w = 0
    j = 0
    while j<max_w:
      for_norm = cell_array[h:h+block[0],w:w+block[1]]
      mag = np.linalg.norm(for_norm)
      arr_list = (for_norm/mag).flatten().tolist()
      #print("hello")
      print(len(arr_list))
      print(arr_list)
      block_list.extend(arr_list) #arr_list
      j += 1
      w += 1

    i += 1
    h += 1

	#returns a vextor array list of 7524 elements
  return block_list


images_hog_features = []

In [ ]:
import numpy as np
import math
mag = [[100,100,100,100,100,100],
       [100,100,100,100,100,100],
       [100,100,100,100,100,100],
       [100,100,100,100,100,100],
       [100,100,100,100,100,100],
       [100,100,100,100,100,100]]
mag = np.array(mag)
print(mag.shape)
angle = [[19,180,0,170,171,5],
         [165,30,10,25,145,75],
         [19,15,155,169,170,175],
         [19.04,170.56,25.67,10.001,15.25,17.89],
         [125.04,168.008,89,24,0.56,0.001],
         [66.36,36.66,24.44,1.23,12.34,123.4]]
angle = np.array(angle)
print(angle.shape)
       

(6, 6)
(6, 6)


In [ ]:
bloc = create_hog_features(angle,mag)

[[ 19. 180.   0.]
 [165.  30.  10.]
 [ 19.  15. 155.]]
[[100 100 100]
 [100 100 100]
 [100 100 100]]
[385. 215.   0.   0.   0.   0.   0. 100. 200.]
[[170. 171.   5.]
 [ 25. 145.  75.]
 [169. 170. 175.]]
[[100 100 100]
 [100 100 100]
 [100 100 100]]
[130.  75.   0.  75.  25.   0.  25.  80. 490.]
[[ 19.04  170.56   25.67 ]
 [125.04  168.008  89.   ]
 [ 66.36   36.66   24.44 ]]
[[100 100 100]
 [100 100 100]
 [100 100 100]]
[107.05 262.45  51.5   86.8   95.    24.8   75.2    9.96 187.24]
[[1.0001e+01 1.5250e+01 1.7890e+01]
 [2.4000e+01 5.6000e-01 1.0000e-03]
 [1.2300e+00 1.2340e+01 1.2340e+02]]
[[100 100 100]
 [100 100 100]
 [100 100 100]]
[511.55  147.405   0.      0.      0.     33.     67.      0.    141.045]
36
[0.39086543732364315, 0.21827550395995657, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1015234902139333, 0.2030469804278666, 0.1319805372781133, 0.07614261766044997, 0.0, 0.07614261766044997, 0.025380872553483324, 0.0, 0.025380872553483324, 0.08121879217114664, 0.4974651020482731, 0.108680896274

In [ ]:
print