<a href="https://colab.research.google.com/github/harshithard/ComputerVision/blob/main/Testing_prewitt's_operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math
def prewitt_operator(gray_img):
  h, w = np.shape(gray_img)[0], np.shape(gray_img)[1]
  # define filters
  horizontal = np.array([[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]])  # s2
  vertical = np.array([[1, 1, 1], [0, 0, 0], [-1, -1, -1]])  # s1
  # define images with 0s
  newgradientImage = np.zeros((h, w))
  gradient_angles = np.zeros((h, w))
  horizontalGrad = np.zeros((h, w))
  verticalGrad = np.zeros((h, w))

  # offset by 1
  for i in range(1, h - 1):
      for j in range(1, w - 1):
        
        horizontalGrad[i][j] = np.sum(np.multiply(gray_img[i-1:i+2,j-1:j+2],horizontal))

        #print(gray_img[i-1:i+2,j-1:j+2])
        verticalGrad[i][j] = np.sum(np.multiply(gray_img[i-1:i+2,j-1:j+2],vertical))
        #print(verticalGrad,horizontalGrad)
        #print(horizontalGrad)
        #print(verticalGrad)
        mag = (np.sqrt(pow(horizontalGrad[i][j], 2.0) + pow(verticalGrad[i][j], 2.0)))
          #print(mag)
        #mag = abs(horizontalGrad[i][j])+abs(verticalGrad[i][j])
        if(horizontalGrad[i][j]==0 and verticalGrad[i][j]==0):
          mag=0
          angle = 0
        else:
          angle = math.degrees(math.atan(verticalGrad[i][j]/ horizontalGrad[i][j]))

        #converting negative angles to positive
        angle = angle%360 
        
        #converting them to range [0,180]
        if angle>=180:
          angle-=180
        #print("mag is",mag)
        gradient_angles[i,j] = angle
        newgradientImage[i,j] = mag
  print(newgradientImage.shape)
  print(horizontalGrad)
  print(verticalGrad)
  # normalized_img1 = (255*(newgradientImage - np.min(newgradientImage))/np.ptp(newgradientImage)).astype(int)  
  normalized_img = (newgradientImage/np.amax(newgradientImage))*255
  normalized_img = normalized_img.astype(int)
  #normalized_img = (newgradientImage * np.max(newgradientImage))/255
  #print(normalized_img)
  #print(gradient_angles)

  return newgradientImage,gradient_angles

In [ ]:
input = [[1,1,1,1,1,1,5],
         [1,1,1,1,1,5,9],
         [1,1,1,1,5,9,9],
         [1,1,1,5,9,9,9],
         [1,1,5,9,9,9,9],
         [1,5,9,9,9,9,9],
         [5,9,9,9,9,9,9]]
input = np.array(input)

mag,ang = prewitt_operator(input)


(7, 7)
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  4. 12. 16.  0.]
 [ 0.  0.  4. 12. 16. 12.  0.]
 [ 0.  4. 12. 16. 12.  4.  0.]
 [ 0. 12. 16. 12.  4.  0.  0.]
 [ 0. 16. 12.  4.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[  0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  -4. -12. -16.   0.]
 [  0.   0.  -4. -12. -16. -12.   0.]
 [  0.  -4. -12. -16. -12.  -4.   0.]
 [  0. -12. -16. -12.  -4.   0.   0.]
 [  0. -16. -12.  -4.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.]]


In [ ]:
mag

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  8., 24., 32.,  0.],
       [ 0.,  0.,  8., 24., 32., 24.,  0.],
       [ 0.,  8., 24., 32., 24.,  8.,  0.],
       [ 0., 24., 32., 24.,  8.,  0.,  0.],
       [ 0., 32., 24.,  8.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [ ]:
ang

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., 135., 135., 135.,   0.],
       [  0.,   0., 135., 135., 135., 135.,   0.],
       [  0., 135., 135., 135., 135., 135.,   0.],
       [  0., 135., 135., 135., 135.,   0.,   0.],
       [  0., 135., 135., 135.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.]])